name: Bygg og deploy
on:
  push:


env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  LATEST_IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generer .npmrc
        run: |
          cat <<'EOF' > .npmrc
              //npm.pkg.github.com/:_authToken=${{ secrets.READER_TOKEN }}
              @navikt:registry=https://npm.pkg.github.com/
              engine-strict=true
              EOF

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.5.6"
          cache-hash: modules-${{ hashFiles('**/deno.jsonc') }}


      - name: Install dependencies
        run: deno install
      
      - name: Run tests
        run: deno test -P

  build:
    name: Bygg
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('**/deno.jsonc')}}

      - name: Generer .npmrc
        run: |
          cat <<'EOF' > .npmrc
              //npm.pkg.github.com/:_authToken=${{ secrets.READER_TOKEN }}
              @navikt:registry=https://npm.pkg.github.com/
              engine-strict=true
              EOF
      
      - name: Bygg og push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ env.VERSION_TAG }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          push_image: true
          dockerfile: Dockerfile
          docker_context: .

      - name: Build static files
        uses: docker/build-push-action@v6
        with:
          target: build-export
          outputs: type=local,dest=build
          secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          context: .

      - name: Upload static files
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamdagpenger
          source: ./build/client
          destination: "/dp-saksbehandling-frontend/"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy til dev-gcp
    if: github.actor != 'dependabot[bot]'
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "https://saksbehandling-dagpenger.ansatt.dev.nav.no"
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ needs.build.outputs.image }},githubSha=${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml,.nais/unleash-apitoken.yaml
          VARS: .nais/vars-dev.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy til prod-gcp
    if: github.ref == 'refs/heads/main'
    needs: [ build,  deploy-dev ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "https://saksbehandling-dagpenger.ansatt.nav.no"
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ needs.build.outputs.image }},githubSha=${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml,.nais/unleash-apitoken.yaml
          VARS: .nais/vars-prod.yaml
          PRINT_PAYLOAD: true
